# Generated by Django 3.2 on 2021-05-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msdzone',
            old_name='zone_location',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='batch',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicinebrand',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='msdzone',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
