# Generated by Django 3.2 on 2021-05-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0002_auto_20210519_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='status',
            field=models.CharField(max_length=30),
        ),
    ]
