# Generated by Django 3.2 on 2021-05-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalroom',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
