# Generated by Django 3.2.2 on 2021-05-10 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='type_id',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Hospital.patienttype'),
            preserve_default=False,
        ),
    ]
