# Generated by Django 3.2 on 2021-05-19 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_auto_20210510_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient_number',
            new_name='serial_number',
        ),
    ]
