# Generated by Django 3.2 on 2021-05-19 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_rename_patient_number_patient_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='other_name',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Hospital.patient'),
        ),
    ]
