# Generated by Django 3.2 on 2021-05-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0004_auto_20210519_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_male',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
