# Generated by Django 3.2 on 2021-05-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0006_auto_20210519_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
